[package]
name = "post_quantum_nft"
authors = ["th0rgal <thomas@starknet.id>"]
version = "0.1.0"

[dependencies]
starknet = "2.3.1"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", rev = "f3e2a5f0547a429c716f32471b06df729cbdfb9f" }
custom_uri = { git = "https://github.com/starknet-id/custom_uri_component.git", rev = "abb2f3d43c7be56dd5cd9f93c33af40b272c2245" }

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true
